### ISSUE TITLE
Do not use SuPeRfail

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/homalg_project#151]
We will remove `SuPeRfail` from the GAP kernel eventually. It would be good if you could stop using it in the future. As far as I can tell, you only use it for `CacheValue` and friends. Two ideas on how to get rid of it:

1. Add a `HasCacheValue` method
2. Change `CacheValue` to return a list, which is either empty (this is the case where you previously used `SuPeRfail`, or contains a single element (the actual cached value).

**Comment by sebasguts** [comment]
There already is a `HasCacheValue`. I think because of the behaviour of the weak pointers, I think it might happen that an entry disappears between calling `HasCacheValue` and `CacheValue`. Is this possible? I think I will go with the second solution, or a variation of it.

Will this happen for 4.8?

**Comment by fingolfin** [comment]
No, this won't happen for 4.8, don't worry. But the sooner you get rid of it, the sooner we can move on with it in GAP ;-)
