### ISSUE TITLE
Segmentation fault triggered in toric varieties

### ISSUE THREAD

**Issue by HereAround** [homalg-project/homalg_project#223]
I use gap 4.10.0 and the recent version of the homalg_project pulled from https://github.com/homalg-project. The following code results in a segmentation fault:

LoadPackage( "ToricVarieties" );
P1 := ProjectiveSpace( 1 );
divisor := DivisorOfGivenClass( P1, [ -1 ] );
p := PolytopeOfDivisor( divisor );

If I am not mistaken, the above triggers the following lines of code

LoadPackage( "NConvex" );
p := PolytopeByInequalities( [[-1,-1],[0,1]] );

Surprisingly, these do not lead to a Seg-fault (on my system).

**Comment by HereAround** [comment]
Update - I investigated this a bit further.

Indeed, the lines 

LoadPackage( "ToricVarieties" );
P1 := ProjectiveSpace( 1 );
divisor := DivisorOfGivenClass( P1, [ -1 ] );
p := PolytopeOfDivisor( divisor );

trigger the method PolytopeByinequalities in the NConvex package (Polytopes.gi, lines 751ff). The critical line is line 764, which checks

IsBound( polyt )

That one fails with Segmentation fault.

Note that AmbientSpaceDimension of a polytope is used for the output string produced for a polytope in the terminal. This information however is provided only after IsBound is being checked. In debugging the IsBound method I therefore had to provide this information by hand, if I want to easily check on the input. Possible improvement on the constructor PolytopeByInequalities in NConvex?

Further, the IsBound method just performs the line

return Length( Cdd_GeneratingRays( ExternalCddPolytope( polytope ) ) ) = 0;

The computation of the Cdd_GeneratingRays fails with the Seg-fault.

A priori this looks like an NConvex problem, but the surprising thing is that I can only trigger this problem when creating this polytope by inequalities in NConvex via ToricVarieties. In contrast, the direct construction in NConvex via

LoadPackage( "NConvex" );
p := PolytopeByInequalities( [[-1,-1],[0,1]] );

completes without Seg-fault.

**Comment by kamalsaleh** [comment]
I find it also surprising. When I run the code given in the issue I also get a segmentation error. 
This error is caused by applying the method **ListToPoly** on a list that is already computed in the C package Cdd, and then returned to Gap. The list should be of length 7. I can display the list without any problems. But a problem happens if list[7]=[ ], where asking for list[7] causes a segmentation error. So something like this happens:

```
# list is returned to Gap from C function
Display( list );
[ 2, 0, 0, 0, 2, [  ], [  ] ]
list[7];
segmentation error!
```
I applied a trick to handle this situation, but the main reason why I can display but not ask for the 7'th entry is still not clear to me.

See: `https://github.com/kamalsaleh/CddInterface/commits/master`

**Comment by HereAround** [comment]
Very good. With this change, the error has disappeared on my system.

I updated the tests (and also documentation) of toric varieties, so that the above lines of code are checked by maketest.
